# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ramblings of a grumpy old developer
copyright_name: Richard Parry
description: > # this means to ignore newlines until "baseurl:"
  Java - SQL developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daisonp.github.io" # the base hostname & protocol for your site

github_username:  daisonp
email_username: richard.w.parry@gmail.com

# Address information
#address_street:
#address_city:
#address_state:
#address_zip:

# Build settings
markdown: kramdown
highlighter: rouge
permalink:  /blog/:year/:month/:day/:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
