# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Richard Parry - Ramblings of a grumpy old developer
copyright_name: Richard Parry
email: richard.w.parry@gmail.com
description: Java - Spring - SQL - Javascript - Node

intro:
  heading: Grumpy old developer
  lead-in: Ramblings of a

navbar:
  brand: Daison P


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daisonp.github.io" # the base hostname & protocol for your site

social:
  - title: atom
    url: pages/blog/atom.xml
    font-class: fa-rss
  - title: bitbucket
    url: https://bitbucket.org/richard_parry/
    font-class: fa-bitbucket
  - title: github
    url: https://github.com/daisonp/
    font-class: fa-github
  - title: google-plus
    url: https://plus.google.com/102739314995618344469
    font-class: fa-google-plus
  - title: linkedin
    url: http://linkedin.com
    font-class: fa-linkedin-square
  - title: email
    url: mailto:richard.w.parry@gmail.com
    font-class: fa-envelope



# Address information
#address_street:
#address_city:
#address_state:
#address_zip:

# Build settings
markdown: kramdown
highlighter: rouge
permalink:  pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
